use_frameworks!

platform :ios, '10.0'

target 'XKSignatureCanvasView_Example' do
  pod 'XKSignatureCanvasView', :path => '../'

  target 'XKSignatureCanvasView_Tests' do
    inherit! :search_paths

    
  end
end
